language: node_js
node_js:
- 12
- 11

install:
  - npm install
script:
  - npm run clean
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: disu
  repo: liaooliver/deploy
  target_branch: master

