language: node_js
node_js:
- 12

# install:
#   - npm install
before_deploy:
  - npm run build

deploy:
  provider: s3
  access_key_id: $pub_id
  secret_access_key: $priv_key
  bucket: "cherrichat"
  skip_cleanup: true
  region: "ap-southeast-1"

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local_dir: dist
#   repo: liaooliver/deploy
#   target_branch: master
