language: node_js
node_js:
- 12
- 11

install:
    - npm install
script:
    - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  repo: liaooliver/HomeWork
  target_branch: master

