language: node_js
node_js:
- 12
- 11

deploy:
  provider: s3
  access_key_id: $aws_id
  secret_access_key: $aws_key
  bucket: cherrichat
  skip_cleanup: true
  region: Asia Pacific (Singapore) ap-southeast-1