language: node_js
node_js:
- 12
- 11

install:
  - npm install

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  repo: liaooliver/deploy
  target_branch: master

